name: Workflow to run Terraform Code

on:
    push:
        branches: ["main"]
    pull_request: 
        branches: ["main"]
    workflow_dispatch:

jobs:
    build_website:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.1.7"

            - name: setup AWS Cli
              run: |
                python -m pip install awscli
                aws --version
                aws s3 ls
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: Terraform init
              run: |
                export TF_LOG="TRACE"
                terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            - name: Terraform format
              run: terraform fmt
            - name: Terraform validate
              run: terraform validate
            - name: Terraform plan
              run: terraform plan
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            - name: Terraform apply
              run: terraform apply --auto-approve
              env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build_website
    #     steps:
    #         - name: Checkout repository
    #           uses: actions/checkout@v4

    #         - name: setup Terraform
    #           uses: hashicorp/setup-terraform@v3
    #           with:
    #             terraform_version: "1.1.7"

    #         - name: setup AWS Cli
    #           run: |
    #             python -m pip install awscli
    #           env:
    #             AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #             AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #             AWS_REGION: ${{ secrets.AWS_REGION }}

    #         - name: Terraform init
    #           run: terraform init
    #         - name: Terraform apply
    #           run: terraform apply --auto-approve