name: Workflow to run Terraform Code

on:
    push:
        branches: ["main"]
    pull_request: 
        branches: ["main"]
    workflow_dispatch:

jobs:
    build_website:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout repository
              uses: actions@checkout@v4

            - name: setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.1.7"
            - name: setup AWS Cli
              run: |
                $ sudo python -m pip install awscli
              env:
                AWS_ACCESS_KEY_ID: ${{ "secrets.AWS_ACCESS_KEY_ID" }}
                AWS_SECRET_ACCESS_KEY: ${{ "secrets.AWS_SECRET_ACCESS_KEY" }}
                AWS_REGION: ${{ "AWS_REGION" }}
            - name: Terraform init
              run: terraform init
            - name: Terraform format
              run: terraform fmt
            - name: Terraform validate
              run: terraform validate
            - name: Terraform plan
              run: terraform plan
    deploy:
        runs-on: ubuntu-latest
        environment: staging
        steps:
            - name: Checkout repository
              uses: actions@checkout@v4

            - name: setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: "1.1.7"
            - name: setup AWS Cli
              run: |
                $ sudo python -m pip install awscli
              env:
                AWS_ACCESS_KEY_ID: ${{ "secrets.AWS_ACCESS_KEY_ID" }}
                AWS_SECRET_ACCESS_KEY: ${{ "secrets.AWS_SECRET_ACCESS_KEY" }}
                AWS_REGION: ${{ "AWS_REGION" }}
            - name: Terraform init
              run: terraform init
            - name: Terraform apply
              run: terraform apply --auto-approve